### ISSUE TITLE
Delete individual Record

### ISSUE THREAD

**Issue by shakyink** [Greenstand/treetracker-admin#4]
Each individual record should be able to be deleted from the collection of records returned from the api. Deleted record should also be seen deleted in the database.

This should be implemented by using the 'active' boolean field on a tree, rather than removing records, this boolean should be set to 'false'.

**Comment by deepwinter** [comment]
This doesn't appear to be working yet.

**Comment by deepwinter** [comment]
Deletion fails when there is a note attached

Mar 20 20:56:18 dev-admin node[12791]: Error committing transaction error: update or delete on table "trees" violates foreign key constraint "note_trees_ibfk_1" on table "note_t
Mar 20 20:56:18 dev-admin node[12791]:     at Connection.parseE (/root/treetracker-admin-api/node_modules/pg/lib/connection.js:545:11)
Mar 20 20:56:18 dev-admin node[12791]:     at Connection.parseMessage (/root/treetracker-admin-api/node_modules/pg/lib/connection.js:370:19)
Mar 20 20:56:18 dev-admin node[12791]:     at Socket.<anonymous> (/root/treetracker-admin-api/node_modules/pg/lib/connection.js:113:22)
Mar 20 20:56:18 dev-admin node[12791]:     at Socket.emit (events.js:180:13)
Mar 20 20:56:18 dev-admin node[12791]:     at addChunk (_stream_readable.js:269:12)
Mar 20 20:56:18 dev-admin node[12791]:     at readableAddChunk (_stream_readable.js:256:11)
Mar 20 20:56:18 dev-admin node[12791]:     at Socket.Readable.push (_stream_readable.js:213:10)
Mar 20 20:56:18 dev-admin node[12791]:     at TCP.onread (net.js:578:20)

**Comment by deepwinter** [comment]
I think it makes sense to deactivate rather than actually delete records.

**Comment by iremaka** [comment]
Issue Moved to "[Delete record using boolean 'active' field rather than actually deleting. #5](https://github.com/Greenstand/treetracker-admin-api/issues/5)"
